### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [steve-mcclellan/splurty#1]
On mobile things don't look as good as they could be.
 
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
 
Let me know in the comments once you figured that step out :)

**Comment by steve-mcclellan** [comment]
OK, I've added a viewport meta tag. Unfortunately, I don't have a working smartphone at the moment (a new one's on the way), so I can't test it myself right now. Please let me know how it looks.

**Comment by BillyMassey** [comment]
Looks good. :+1:
